#!/usr/bin/env node

/**
 * Module dependencies.
 */
var app = require('../app');  // Change this to point to 'app.js'
var debug = require('debug')('final:server');
var http = require('http');

/**
 * Get port from environment and store in Express.
 */

// /var port = normalizePort(process.env.PORT || '3000');
// app.set('port', port);

/**
 * Create HTTP server.
 */
var server = http.createServer(app);


/**
 * Event listener for HTTP server "listening" event.
 */
function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}

